### ISSUE TITLE
Game Suggestion: Planetwars

### ISSUE THREAD

**Issue by marshl** [mleonard87/merknera#1]
A game where two (or more) players begin the game owning a planet in opposite corners of a two dimensional field of planets. Every other planet on the map is owned by a neutral player, and have a static number of ships. The starting planet of each player also starts with a number of ships, however the ship count on owned planets steadily increase at a rate dependant on the size of the planet. Players can send ships from a planet to other planets in the system, which subtracts the number of ships from the total of that planet and begins moving the fleet through space. When the fleet arrives at a planet, if the planet is friendly then the fleet count is added to the planet count. If the planet is enemy or neutral, the number of ships on the planet is subtracted from the fleet. If there were more ships in the fleet, then the owner of the fleet gains control of the planet with the leftover ships as the new planet ship count, otherwise the fleet is destroyed and the planet remains under the original owners control.

The game ends when all planets have been captured by any given player, otherwise the player with the highest ship count once the timer runs out wins.

Here is an example C++ program that runs in realtime, modifications may have to be made to make the game turn based:
[PlanetWars.zip](https://github.com/mleonard87/merknera/files/239706/PlanetWars.zip)

**Comment by tombasche** [comment]
A game where your bot has to get through a maze, possibly avoiding traps along the way. Cooler if we all were on the same maze and bots could attack other bots
